### ISSUE TITLE
怎么给指定的设备发送消息？

### ISSUE THREAD

**Issue by artillerymans** [pocmo/Android-Network-Intents#6]
例如：同网络下总共3台设备，名字分别：A,B,C;
场景：A设备发送给B设备，但是C设备我不想让它接收到。
类似上面的场景我需要怎么去做？感谢您的回复

**Comment by pocmo** [comment]
All devices listening will receive all messages (that's just how multicast works) . However if you include some kind of "receiver" (or other filter mechanism) into the message then other devices can ignore those messages.
